version: "3"

services:
  frontend:
    container_name: react-frontend
    build: ./frontend/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - PORT=${FRONTEND_PORT}
    networks:
      - mern-network
  
  backend:
    container_name: express-backend
    build: ./backend/
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${BACKEND_PORT}
    networks:
      - mern-network
  
  database:
    container_name: mongodb-database
    image: mongo
    volumes:
      - /home/d/triviagame-mongodb-backup:/data/db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_PASS=Jv75Nrir7d7yT7lG
      - PORT=3001
    networks:
      - mern-network
  
  microservice:
    container_name: leaderboard-fastapi
    build: ./leaderboard-fastapi/
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern-network

volumes:
  triviagame-mongodb-backup:

networks:
  mern-network:
    driver: bridge